[[page]]
path = "Home.py"
icon = "ğŸ“"
name = "Home"

[[section]]
name = "Player"
icon = "ğŸ“"
is_section = true

[[section.page]]
path = "pages/Player/player_batting_season.py"
icon = "ğŸ“"
name = "Batting"

[[section.page]]
path = "pages/Player/player_pitching_season.py"
icon = "ğŸ“"
name = "Pitching"


[[section]]
name = "References"
icon = "ğŸ“"
is_section = true

[[section.page]]
path = "pages/References/Data_Dictionary.py"
icon = "ğŸ“"
name = "Data Dictionary"
